### ISSUE TITLE
create mockup for training page

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/pds-site-app#1]
Create a mock up of a new page for https://pds.jpl.nasa.gov/datastandards/training/

The new page can be inspired by this page: https://pds.jpl.nasa.gov/datasearch/subscription-service/data-release-calendar.shtml

We would have a table to hold the info and users could search and find the training materials they want.

We would like the training web pages to be easily integrated with the future styling but the page should work on the current web site.

**Comment by jordanpadams** [comment]
[PdsTraining.pdf](https://github.com/NASA-PDS/pds-site-app/files/5037902/PdsTraining.pdf)
